"""
Auckland Explorer - Pydantic Structural Contract Layer
Protects the platform boundary from volatile external API outputs.
"""

from pydantic import BaseModel, Field, AnyHttpUrl
from typing import List, Optional


class GeolocationCoordinates(BaseModel):
    # Validates that the user's coordinates are inside the Auckland region.
    latitude: float = Field(..., ge=-37.3000, le=-36.3000)
    longitude: float = Field(..., ge=174.4000, le=175.3000)


class DestinationMatchItem(BaseModel):
    # Represents ONE destination recommendation.
    place_name: str = Field(..., min_length=2)

    # Category returned by the place-search/recommendation system.
    category: str = Field(
        ...,
        description="Dynamic category derived from live place data."
    )

    # Why the AI selected this destination.
    relevance_rationale: str = Field(
        ...,
        description="Dynamically synthesized justification from the AI model."
    )

    # Official/reference URL for the destination.
    auckland_council_url: AnyHttpUrl = Field(
        ...,
        description="Verified authority reference endpoint."
    )


class DestinationMatchResponse(BaseModel):
    # Greeting shown to the user.
    cultural_greeting: str = Field(
        ...,
        description="Contextual Te Reo greeting dynamically generated by the AI."
    )

    # Maximum of five recommendations.
    # Pydantic v2 uses max_length instead of max_items.
    recommended_destinations: List[DestinationMatchItem] = Field(
        ...,
        max_length=5
    )

    # Can contain a safety message or be None.
    environmental_safety_notice: Optional[str] = Field(None)
class ChatRequest(BaseModel):
    # The user's current location.
    coordinates: GeolocationCoordinates

    # The message typed into the chat.
    user_intent_prompt: str

    # Preferences selected before the user starts chatting.
    user_preferences: dict = {}